### ISSUE TITLE
Send nested maps to graphite

### ISSUE THREAD

**Issue by shindo** [noxiouz/Combaine#41]
Currently one can send Map to graphite if its values are either Value or Array:
https://github.com/noxiouz/Combaine/blob/d31b51ab8b58d535300a4467241fc5d5c57de4d0/senders/graphite/graphite.go#L46-L54

It would be useful to be able to send nested maps, e.g.:
```(json)
{
  "a": 0,
  "b": [1, 2, 3],
  "c": {
    "d": [4, 5, 6],
    "e": {
      "f": 7
    }
  }
}
```

**Comment by noxiouz** [comment]
It's already supported
https://github.com/noxiouz/Combaine/blob/d31b51ab8b58d535300a4467241fc5d5c57de4d0/senders/graphite/graphite_test.go

**Comment by shindo** [comment]
I got this log:
```
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c task started
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c {'sata02h': ('XXX',), 'sata01h': ('XXX',)}
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c Send to metrics custom
app/custom: 6c379299028ecbc3d5e91d61501e6b7c Result of group aggreagtion {'top_rates': {'p90': 2016258.6, 'p75': 2016258.6, 'p50': 1.0666666666666667, 'p95': 2016258.6, 'p100': 2016258.6}}
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c name metrics subgroup elliptics-sata01h result {'top_rates': {'p90': 2016258.6, 'p75': 2016258.6, 'p50': 1.0666666666666667, 'p95': 2016258.6, 'p100': 2016258.6}}
app/custom: 6c379299028ecbc3d5e91d61501e6b7c Result of group aggreagtion {'top_rates': {'p90': 5190416.533333333, 'p75': 5190416.533333333, 'p50': 1.0666666666666667, 'p95': 5190416.533333333, 'p100': 5190416.533333333}}
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c name metrics subgroup elliptics-sata02h result {'top_rates': {'p90': 5190416.533333333, 'p75': 5190416.533333333, 'p50': 1.0666666666666667, 'p95': 5190416.533333333, 'p100': 5190416.533333333}}
app/custom: 6c379299028ecbc3d5e91d61501e6b7c Result of group aggreagtion {'top_rates': {'p90': 7206675.133333333, 'p75': 7206675.133333333, 'p50': 2.1333333333333333, 'p95': 7206675.133333333, 'p100': 7206675.133333333}}
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c name metrics ALL {'top_rates': {'p90': 7206675.133333333, 'p75': 7206675.133333333, 'p50': 2.1333333333333333, 'p95': 7206675.133333333, 'p100': 7206675.133333333}} 2
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c Send to graphite: {'metrics': {'elliptics': {'top_rates': {'p90': 7206675.133333333, 'p75': 7206675.133333333, 'p50': 2.1333333333333333, 'p95': 7206675.133333333, 'p100': 7206675.133333333}}, 'elliptics-sata01h': {'top_rates': {'p90': 2016258.6, 'p75': 2016258.6, 'p50': 1.0666666666666667, 'p95': 2016258.6, 'p100': 2016258.6}}, 'elliptics-sata02h': {'top_rates': {'p90': 5190416.533333333, 'p75': 5190416.533333333, 'p50': 1.0666666666666667, 'p95': 5190416.533333333, 'p100': 5190416.533333333}}}}
app/graphite: 6c379299028ecbc3d5e91d61501e6b7c Send combaine.elliptics.metrics.top_rates map[p100:7.206675133333333e+06 p90:7.206675133333333e+06 p75:7.206675133333333e+06 p50:2.1333333333333333 p95:7.206675133333333e+06] 1432140551
app/graphite: 6c379299028ecbc3d5e91d61501e6b7c Send combaine.elliptics_sata01h.metrics.top_rates map[p90:2.0162586e+06 p75:2.0162586e+06 p50:1.0666666666666667 p95:2.0162586e+06 p100:2.0162586e+06] 1432140551
app/graphite: 6c379299028ecbc3d5e91d61501e6b7c Send combaine.elliptics_sata02h.metrics.top_rates map[p90:5.190416533333333e+06 p75:5.190416533333333e+06 p50:1.0666666666666667 p95:5.190416533333333e+06 p100:5.190416533333333e+06] 1432140551
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c res for graphite is DONE
app/aggregate: 6c379299028ecbc3d5e91d61501e6b7c Result {'metrics': {'elliptics': {'top_rates': {'p90': 7206675.133333333, 'p75': 7206675.133333333, 'p50': 2.1333333333333333, 'p95': 7206675.133333333, 'p100': 7206675.133333333}}, 'elliptics-sata01h': {'top_rates': {'p90': 2016258.6, 'p75': 2016258.6, 'p50': 1.0666666666666667, 'p95': 2016258.6, 'p100': 2016258.6}}, 'elliptics-sata02h': {'top_rates': {'p90': 5190416.533333333, 'p75': 5190416.533333333, 'p50': 1.0666666666666667, 'p95': 5190416.533333333, 'p100': 5190416.533333333}}}}
```

It looks like Combaine tried to send map.

Also, I can't find any recursive calls within `sendInternal` function for Map data type:
https://github.com/noxiouz/Combaine/blob/d31b51ab8b58d535300a4467241fc5d5c57de4d0/senders/graphite/graphite.go#L87-L128

**Comment by shindo** [comment]
Am I using an obsolete version of Combaine?
```
ii  combaine-core            0.7.0.1-rc24    Core task handlers.
ii  combaine-plugin-mysql    0.7.0.1-rc24    Plugin which allows to use MySQL queries.
ii  combaine-presetting      0.7.0.1-rc24    Combaine environment checker.
ii  combainer                0.7.0.1-rc24    Combaine dispather daemon.
```

**Comment by noxiouz** [comment]
Nope. Current version: https://github.com/noxiouz/Combaine/blob/v0.7/debian/changelog rc45

**Comment by shindo** [comment]
Well... Probably this was fixed in rc25:
```
combaine (0.7.0.1-rc25) unstable; urgency=low

  * [Graphite] Fix reflection checker in case of map-in-map
```

**Comment by noxiouz** [comment]
Nemaloveroyatno :)

**Comment by shindo** [comment]
With rc45, I have the same problem:
```
app/graphite: Send combaine.elliptics_sata02h.metrics.top_rates map[p75:619723.4666666667 p50:0.7 p95:619723.4666666667 p100:619723.4666666667 p90:619723.4666666667] 1432146870
```

And none of these in graphite.

**Comment by shindo** [comment]
And here is no case for Map in switch:
https://github.com/noxiouz/Combaine/blob/8927111bc619f6bcc6c1239d6c914d17039107fd/senders/graphite/graphite.go#L112-L143

**Comment by noxiouz** [comment]
Ok, I will add. Thank you!

**Comment by noxiouz** [comment]
Do you need this feature ASAP?

**Comment by shindo** [comment]
No, it's up to you.

**Comment by noxiouz** [comment]
Fixed via 20ac16637bf1c51ddcb438e0e35a56cb60f0c2e8

**Comment by shindo** [comment]
Thanks!

**Comment by shindo** [comment]
Unfortunately, r46 does not fix the issue.
And the behaviour is the same as specified above (it tries to send map).
